package Protocol;

public enum ProtocolResponseType {
    USER_NAMES, LOGIN_SUCCESS, PROFILE, PUBLIC_INFO, CONVERSATION_TITLES, CONVERSATION, CSV_EXPORT, LOGOUT_SUCCESS, ACCOUNT_DELETION, DASHBOARD
}
